### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by jkcgs** [austinv11/Discord4J#16]
I'm using the 2.2.6 version (from Maven), in [this project](https://github.com/jkcgs/DiscordChat) (a Spigot plugin), and I'm getting this exception on the console. I don't know if this has been fixed on the current snapshot, but looking at the sources (Channel.java:169), that function has not been changed. It's not harmful to the plugin, but it's kinda annoying seeing this on the console.

```txt
[15:17:52 WARN]: java.util.ConcurrentModificationException
[15:17:52 WARN]:        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
[15:17:52 WARN]:        at java.util.ArrayList$Itr.next(ArrayList.java:851)
[15:17:52 WARN]:        at sx.blah.discord.handle.impl.obj.Channel.getMessageByID(Channel.java:169)
[15:17:52 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.getMessageFromJSON(DiscordUtils.java:316)
[15:17:52 WARN]:        at sx.blah.discord.api.internal.DiscordWS.messageCreate(DiscordWS.java:303)
[15:17:52 WARN]:        at sx.blah.discord.api.internal.DiscordWS.onMessage(DiscordWS.java:144)
[15:17:52 WARN]:        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
[15:17:52 WARN]:        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
[15:17:52 WARN]:        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
[15:17:52 WARN]:        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
[15:17:52 WARN]:        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
[15:17:52 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

Current main classes that have relation with this function are `src/main/java/com/makzk/spigot/discordchat/DiscordListener.java` and `src/main/java/com/makzk/spigot/discordchat/MinecraftListener.java`.

**Comment by austinv11** [comment]
Try version 2.2.7 and let me know if this is stil an issue.

**Comment by jkcgs** [comment]
Thank you!

**Comment by jkcgs** [comment]
Looks like that fixed it. Thanks again :smile:
