### ISSUE TITLE
Login Error: java.lang.NoClassDefFoundError: org/slf4j/Marker

### ISSUE THREAD

**Issue by bignose956** [austinv11/Discord4J#273]
### Prerequisites
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Getting the following error on `clientBuilder.login();`:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/Marker
	at sx.blah.discord.api.ClientBuilder.build(ClientBuilder.java:261)
	at sx.blah.discord.api.ClientBuilder.login(ClientBuilder.java:281)
	at Example.createClient(Example.java:12)
	at Example.main(Example.java:24)
Caused by: java.lang.ClassNotFoundException: org.slf4j.Marker
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more
```

### Steps to Reproduce
1. Login bot using `IDiscordClient client = Example.createClient("token", true);` (Full method at https://github.com/austinv11/Discord4J#starting-with-the-api)
2. Error

...

**Expected behavior:** [Login the bot]

**Actual behavior:** [Error at login()]

**Stacktrace (if applicable):**

**Version affected:** [2.8.2 (Latest)]

### Additional Information
[I am using Eclipse Neon on Windows 7. I am not using maven or gradle.]

**Comment by austinv11** [comment]
`I am not using maven or gradle.` That is your issue. You are missing the slf4j dependency. Use the shaded jar if you wanna use this library without a dependency management system.

**Comment by bignose956** [comment]
I am using the shared jar...

**Comment by bignose956** [comment]
Oops. I misread the tutorial you had :P
