### ISSUE TITLE
Exception when trying to receive voice

### ISSUE THREAD

**Issue by Edvinas01** [austinv11/Discord4J#314]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I'm trying to create a bot which would receive voice input from some user and do some processing with the audio data. Upon registering a receiver and waiting for a user to speak, an exception is thrown.

### Steps to Reproduce
1. Register a `IAudioReceiver` in the application.
```java
client.getDispatcher().registerListener(new IListener<MessageEvent>() {

    @Override
    public void handle(MessageEvent event) {
        if ("register_voice".equals(event.getMessage().getContent())) {
            event.getGuild().getAudioManager()
                    .subscribeReceiver((audio, user, sequence, timestamp) -> {
                        /* Do things with audio */
                    });
        }
    }
});
```
2. Run the application.
3. Move the bot to a voice channel with a user.
4. Wait for the user to speak.

**Expected behavior:** 
Audio data should be received without any exceptions.

**Actual behavior:**
Exception is thrown and no audio data was received.

**Stacktrace:** 
```
Exception in thread "D4J AudioThread" java.lang.ExceptionInInitializerError
	at sx.blah.discord.api.internal.Opus.<clinit>(Opus.java:71)
	at sx.blah.discord.api.internal.OpusUtil.newDecoder(OpusUtil.java:38)
	at sx.blah.discord.handle.audio.impl.AudioManager.lambda$new$2(AudioManager.java:46)
	at sx.blah.discord.util.Lazy.get(Lazy.java:36)
	at sx.blah.discord.handle.audio.impl.AudioManager.receiveAudio(AudioManager.java:113)
	at sx.blah.discord.api.internal.UDPVoiceSocket.lambda$new$1(UDPVoiceSocket.java:99)
	at sx.blah.discord.api.internal.UDPVoiceSocket.lambda$begin$2(UDPVoiceSocket.java:153)
	at sx.blah.discord.util.HighPrecisionRecurrentTask.run(HighPrecisionRecurrentTask.java:62)
Caused by: java.lang.IllegalArgumentException: Invalid sizeof type 4
	at com.sun.jna.Native.sizeof(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:161)
	... 8 more
```

**Version affected:** 
2.8.3

### Additional Information
Windows 10 Pro 64bit
jdk-8u131-windows-x64

**Comment by GrandPanda** [comment]
This could be caused by having multiple versions of JNA on your classpath.

**Comment by Edvinas01** [comment]
I'm using Gradle to manage dependencies so that shouldn't be the case I'm guessing? Also manually checking the project classpath list via `System.getProperty("java.class.path").split(";");` I can't seem to find any JNA duplicates. 

To test this a bit more, I downloaded the Discord4j project, cleared Maven cache and created a test case to try and reproduce this (calling the method directly which causes the exception):
```java
package sx.blah.discord;

import org.junit.Test;
import sx.blah.discord.api.internal.OpusUtil;

public class VoiceReceiveTest {

    @Test
    public void createDecoder() throws Exception {
        OpusUtil.newDecoder(2);
    }
}
```

The exception is still thrown:
```
java.lang.ExceptionInInitializerError
	at sx.blah.discord.api.internal.Opus.<clinit>(Opus.java:71)
	at sx.blah.discord.api.internal.OpusUtil.newDecoder(OpusUtil.java:38)
	at sx.blah.discord.VoiceReceiveTest.createDecoder(VoiceReceiveTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Invalid sizeof type 4
	at com.sun.jna.Native.sizeof(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:161)
	... 25 more
```

However if I update the projects JNA to `4.4.0`, pom.xml:
```xml
<dependency>
	<groupId>net.java.dev.jna</groupId>
	<artifactId>jna</artifactId>
	<version>4.4.0</version>
</dependency>
```

And update the test a bit:
```java
@Test
public void createDecoder() throws Exception {
	System.setProperty("jna.nosys", "true");
	OpusUtil.newDecoder(2);
}
```

The decoder seems to be created. I also tested this in my project and the voice seems to be received as excepted. Tomorrow I can test this on another Windows 64-bit machine and will report the results.

**Comment by ArsenArsen** [comment]
You probably have a faulty jna library in your system.

**Comment by Edvinas01** [comment]
The check sums seem to match of remote [GitHub version](https://github.com/java-native-access/jna/releases/tag/4.3.0) of JNA with the local version downloaded by Maven:

```
$ md5sum jna-4.3.0-local.jar
d44a0d3bcb98b1aace47610bfb0c0758 *jna-4.3.0-local.jar

$ md5sum jna-4.3.0-git.jar
d44a0d3bcb98b1aace47610bfb0c0758 *jna-4.3.0-git.jar
```

**Comment by ArsenArsen** [comment]
I meant if nosys fixed it that means it's using the embedded JNA dll, instead of the system one, which means the one it finds in the system is probably bad. Print your entire classpath and go through the directories. You'll probably find a JNA jar

**Comment by Edvinas01** [comment]
Hmm, interesting, I added that statement initially since version `4.4.0` was complaining, didn't put too much though into it. It seems to work with `4.3.0` as well. Where could this system JNA version be loaded from? The classpath is pointing to a Maven dir:
```
C:\Users\edvin\.m2\repository\net\java\dev\jna\jna\4.3.0\jna-4.3.0.jar
```

**Comment by ArsenArsen** [comment]
Probably that jar. Keep in mind if youre running from an IDE it is most likely running a command with all your dependencies in the classpath

**Comment by Edvinas01** [comment]
You're right, tested this today on another Windows machine and it seems to be working just fine. I'll just use `jna.nosys` in the faulty one. Thanks for the help!
