### ISSUE TITLE
Login Error : NoClassDefFoundError org/apache/http/client/methods/HttpUriRequest

### ISSUE THREAD

**Issue by engboris** [austinv11/Discord4J#92]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [#java_discord4j channel on 
the Discord API Server](https://discord.gg/0SBTUU1wZTU7PCok)
* [ ] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description

Hello,

I'm getting the following error : 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
	at sx.blah.discord.api.internal.DiscordClientImpl.validateToken(DiscordClientImpl.java:224)
	at sx.blah.discord.api.internal.DiscordClientImpl.login(DiscordClientImpl.java:209)
	at sx.blah.discord.api.ClientBuilder.login(ClientBuilder.java:144)
	at com.darichey.tutorial_bot.TutorialBot.main(TutorialBot.java:11)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpUriRequest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

while trying to login with a ClientBuilder. I'm using this serie of tutorials : http://blog.darichey.com/

### Steps to Reproduce
1. Login a bot using client = new ClientBuilder().withToken("TOKEN").login();
2. Error

**Expected behavior:** Login the bot

**Actual behavior:** Error at login()

**Stacktrace (if applicable):** 

**Version affected:** 2.5.2

### Additional Information
I'm using Eclipse Neon with Maven and I'm under Windows 10.
It worked well under Windows 7 with Eclipse Luna.
I also tried with Eclipse Luna, IntelliJ and tried to make a new project from scratch. It doesn't work as well.

**Comment by austinv11** [comment]
The only reason that would happen is if your dependency management system (either via your ide or maven) failed to retrieve Discord4J's dependencies, in this case, apache http client. Would you mind joining us on the Discord4J guild (https://discord.gg/VCqpc)? It would be easier to debug this together.
